erDiagram
    core_personas ||--o{ core_estudiantes : "perfil"
    core_personas ||--o{ core_docentes : "perfil"
    core_unidades_didacticas ||--o{ mod02_clases_docente : "dictada en"
    core_docentes ||--o{ mod02_clases_docente : "titular"
    core_aulas ||--o{ mod02_clases_docente : "aula"
    mod02_clases_docente ||--o{ mod02_sesiones_clase : "18 semanas"
    mod02_clases_docente ||--o{ mod02_clase_horarios : "horario"
    mod02_sesiones_clase ||--o{ mod02_asistencias : "asistencias"
    core_estudiantes ||--o{ mod02_asistencias : "asiste"
    mod02_asistencias ||--o| mod02_justificaciones : "justifica"
    core_estudiantes ||--o{ mod02_justificaciones : "solicita"
    core_docentes ||--o{ mod02_justificaciones : "resuelve"