-- =============================================================================
-- STOCKCODE - MODULO 03: INVENTARIO & EQUIPOS
-- PostgreSQL 16 | Esquema: mod03
-- Sistema Web de Gestión de Inventario y Almacenes
-- =============================================================================
-- -----------------------------------------------------------------------------
-- LIMPIEZA DE TABLA DEMO DEL MODULO
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS mod03.t_modulo03_registros CASCADE;

-- -----------------------------------------------------------------------------
-- 1. ESPECIALIDAD
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mod03.especialidad (
    id_especialidad INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    estado VARCHAR(20) NOT NULL DEFAULT 'Activo',
    CONSTRAINT ck_especialidad_estado
        CHECK (estado IN ('Activo', 'Inactivo'))
);

-- -----------------------------------------------------------------------------
-- 2. ALMACEN
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mod03.almacen (
    id_almacen INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_especialidad INTEGER NULL,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    ubicacion VARCHAR(150),
    responsable VARCHAR(150),
    estado VARCHAR(20) NOT NULL DEFAULT 'Activo',

    CONSTRAINT fk_almacen_especialidad
        FOREIGN KEY (id_especialidad)
        REFERENCES mod03.especialidad(id_especialidad),

    CONSTRAINT ck_almacen_estado
        CHECK (estado IN ('Activo', 'Inactivo'))
);

-- -----------------------------------------------------------------------------
-- 3. AMBIENTE
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mod03.ambiente (
    id_ambiente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_especialidad INTEGER NULL,
    nombre VARCHAR(100) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'Activo',

    CONSTRAINT fk_ambiente_especialidad
        FOREIGN KEY (id_especialidad)
        REFERENCES mod03.especialidad(id_especialidad),

    CONSTRAINT ck_ambiente_estado
        CHECK (estado IN ('Activo', 'Inactivo')),

    CONSTRAINT uq_ambiente_especialidad
        UNIQUE (id_especialidad, nombre)
);

-- -----------------------------------------------------------------------------
-- 4. CLASIFICACIONES DE BIEN
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mod03.clasificaciones_bien (
    id_clasificacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL UNIQUE,
    estado VARCHAR(20) NOT NULL DEFAULT 'Activo',

    CONSTRAINT ck_clasificacion_estado
        CHECK (estado IN ('Activo', 'Inactivo'))
);

-- -----------------------------------------------------------------------------
-- 5. BIEN
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mod03.bien (
    id_bien INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_almacen INTEGER NOT NULL,
    id_clasificacion INTEGER NOT NULL,

    cbi VARCHAR(30) NOT NULL UNIQUE,
    codigo_inventario VARCHAR(50) UNIQUE,
    descripcion VARCHAR(150) NOT NULL,
    marca VARCHAR(100),
    modelo VARCHAR(100),
    serie VARCHAR(100) UNIQUE,

    procedencia VARCHAR(30) NOT NULL DEFAULT 'Donación',
    fecha_ingreso DATE NOT NULL DEFAULT CURRENT_DATE,

    estado VARCHAR(30) NOT NULL DEFAULT 'Bueno',
    observacion TEXT,

    CONSTRAINT fk_bien_almacen
        FOREIGN KEY (id_almacen)
        REFERENCES mod03.almacen(id_almacen),

    CONSTRAINT fk_bien_clasificacion
        FOREIGN KEY (id_clasificacion)
        REFERENCES mod03.clasificaciones_bien(id_clasificacion),

    CONSTRAINT ck_bien_procedencia
        CHECK (procedencia IN ('Donación', 'Adquisición', 'Transferencia', 'Otro')),

    CONSTRAINT ck_bien_estado
        CHECK (estado IN (
            'Bueno',
            'Regular',
            'Malo',
            'En reparación',
            'Inoperativo',
            'Baja en trámite',
            'De baja'
        ))
);

-- -----------------------------------------------------------------------------
-- 6. ASIGNACION
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mod03.asignacion (
    id_asignacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_bien INTEGER NOT NULL,
    id_ambiente INTEGER NOT NULL,
    responsable VARCHAR(150),
    fecha_asignacion DATE NOT NULL DEFAULT CURRENT_DATE,
    fecha_fin DATE,
    estado VARCHAR(20) NOT NULL DEFAULT 'Activa',
    observacion TEXT,

    CONSTRAINT fk_asignacion_bien
        FOREIGN KEY (id_bien)
        REFERENCES mod03.bien(id_bien),

    CONSTRAINT fk_asignacion_ambiente
        FOREIGN KEY (id_ambiente)
        REFERENCES mod03.ambiente(id_ambiente),

    CONSTRAINT ck_asignacion_estado
        CHECK (estado IN ('Activa', 'Finalizada')),

    CONSTRAINT ck_asignacion_fechas
        CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_asignacion)
);

-- -----------------------------------------------------------------------------
-- 7. TRANSFERENCIA
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mod03.transferencia (
    id_transferencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_bien INTEGER NOT NULL,
    id_almacen_origen INTEGER NOT NULL,
    id_almacen_destino INTEGER NOT NULL,

    fecha_solicitud TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_salida TIMESTAMP WITH TIME ZONE,
    fecha_recepcion TIMESTAMP WITH TIME ZONE,

    motivo VARCHAR(150) NOT NULL,
    responsable_origen VARCHAR(150),
    responsable_destino VARCHAR(150),

    estado_movimiento VARCHAR(30) NOT NULL DEFAULT 'Pendiente de recepción',
    documento VARCHAR(100),
    observacion TEXT,

    CONSTRAINT fk_transferencia_bien
        FOREIGN KEY (id_bien)
        REFERENCES mod03.bien(id_bien),

    CONSTRAINT fk_transferencia_origen
        FOREIGN KEY (id_almacen_origen)
        REFERENCES mod03.almacen(id_almacen),

    CONSTRAINT fk_transferencia_destino
        FOREIGN KEY (id_almacen_destino)
        REFERENCES mod03.almacen(id_almacen),

    CONSTRAINT ck_transferencia_origen_destino
        CHECK (id_almacen_origen <> id_almacen_destino),

    CONSTRAINT ck_transferencia_estado
        CHECK (estado_movimiento IN (
            'Pendiente',
            'En tránsito',
            'Pendiente de recepción',
            'Recepcionado',
            'Cancelado'
        )),

    CONSTRAINT ck_transferencia_fechas
        CHECK (fecha_salida IS NULL OR fecha_salida >= fecha_solicitud)
);

-- -----------------------------------------------------------------------------
-- 8. INVENTARIO ANUAL
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mod03.inventario_anual (
    id_inventario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_bien INTEGER NOT NULL,
    anio INTEGER NOT NULL,
    fecha_verificacion DATE NOT NULL DEFAULT CURRENT_DATE,
    resultado VARCHAR(20) NOT NULL DEFAULT 'Físico',
    observacion TEXT,

    CONSTRAINT fk_inventario_anual_bien
        FOREIGN KEY (id_bien)
        REFERENCES mod03.bien(id_bien),

    CONSTRAINT ck_inventario_anual_anio
        CHECK (anio BETWEEN 2000 AND 2100),

    CONSTRAINT ck_inventario_anual_resultado
        CHECK (resultado IN ('Físico', 'Faltante', 'Sobrante')),

    CONSTRAINT uq_inventario_anual_bien_anio
        UNIQUE (id_bien, anio)
);

-- =============================================================================
-- INDICES
-- =============================================================================
CREATE INDEX IF NOT EXISTS idx_bien_almacen
    ON mod03.bien(id_almacen);

CREATE INDEX IF NOT EXISTS idx_bien_clasificacion
    ON mod03.bien(id_clasificacion);

CREATE INDEX IF NOT EXISTS idx_bien_estado
    ON mod03.bien(estado);

CREATE INDEX IF NOT EXISTS idx_bien_serie
    ON mod03.bien(serie);

CREATE INDEX IF NOT EXISTS idx_asignacion_bien
    ON mod03.asignacion(id_bien);

CREATE INDEX IF NOT EXISTS idx_asignacion_ambiente
    ON mod03.asignacion(id_ambiente);

CREATE INDEX IF NOT EXISTS idx_transferencia_bien
    ON mod03.transferencia(id_bien);

CREATE INDEX IF NOT EXISTS idx_transferencia_estado
    ON mod03.transferencia(estado_movimiento);

CREATE INDEX IF NOT EXISTS idx_inventario_anual_anio
    ON mod03.inventario_anual(anio);

-- =============================================================================
-- VISTA PARA CONSULTA DEL INVENTARIO
-- =============================================================================
CREATE OR REPLACE VIEW mod03.v_inventario AS
SELECT
    b.id_bien,
    b.cbi,
    b.codigo_inventario,
    b.descripcion,
    cb.nombre AS clasificacion,
    b.marca,
    b.modelo,
    b.serie,
    b.procedencia,
    b.fecha_ingreso,
    b.estado,
    a.nombre AS almacen_actual,
    a.ubicacion AS ubicacion_almacen,
    amb.nombre AS ambiente_actual,
    asg.responsable,
    b.observacion
FROM mod03.bien b
JOIN mod03.almacen a
    ON a.id_almacen = b.id_almacen
JOIN mod03.clasificaciones_bien cb
    ON cb.id_clasificacion = b.id_clasificacion
LEFT JOIN LATERAL (
    SELECT *
    FROM mod03.asignacion ax
    WHERE ax.id_bien = b.id_bien
      AND ax.estado = 'Activa'
    ORDER BY ax.fecha_asignacion DESC, ax.id_asignacion DESC
    LIMIT 1
) AS asg ON TRUE
LEFT JOIN mod03.ambiente amb
    ON amb.id_ambiente = asg.id_ambiente;

-- =============================================================================
-- VISTA PARA TRANSFERENCIAS
-- =============================================================================
CREATE OR REPLACE VIEW mod03.v_transferencias AS
SELECT
    t.id_transferencia,
    b.cbi,
    b.descripcion,
    ao.nombre AS almacen_origen,
    ad.nombre AS almacen_destino,
    t.fecha_solicitud,
    t.fecha_salida,
    t.fecha_recepcion,
    t.estado_movimiento,
    t.motivo,
    t.responsable_origen,
    t.responsable_destino,
    t.documento,
    t.observacion
FROM mod03.transferencia t
JOIN mod03.bien b
    ON b.id_bien = t.id_bien
JOIN mod03.almacen ao
    ON ao.id_almacen = t.id_almacen_origen
JOIN mod03.almacen ad
    ON ad.id_almacen = t.id_almacen_destino;

-- =============================================================================
-- VISTA PARA INVENTARIO ANUAL
-- =============================================================================
CREATE OR REPLACE VIEW mod03.v_inventario_anual AS
SELECT
    ia.id_inventario,
    ia.anio,
    ia.fecha_verificacion,
    ia.resultado,
    b.cbi,
    b.descripcion,
    b.serie,
    a.nombre AS almacen_actual,
    ia.observacion
FROM mod03.inventario_anual ia
JOIN mod03.bien b
    ON b.id_bien = ia.id_bien
JOIN mod03.almacen a
    ON a.id_almacen = b.id_almacen;



-- =============================================================================
-- DATOS DE DEMOSTRACIÓN
-- =============================================================================
-- Estos registros permiten probar el módulo antes de la presentación.
-- Los datos de los equipos se basan en los campos y ejemplos observados en
-- los inventarios institucionales compartidos para el proyecto.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- ALMACENES DE DEMOSTRACIÓN
-- -----------------------------------------------------------------------------

INSERT INTO mod03.almacen (
    id_especialidad,
    nombre,
    ubicacion,
    responsable
)
SELECT
    e.id_especialidad,
    x.nombre,
    x.ubicacion,
    x.responsable
FROM (
    VALUES
        ('Computación e Informática', 'Almacén General', 'Almacén institucional', 'Eduardo - Patrimoniales'),
        ('Computación e Informática', 'Almacén Computación', 'Área de Computación e Informática', 'Encargado de Computación'),
        ('Contabilidad', 'Almacén Contabilidad', 'Área de Contabilidad', 'Encargado de Contabilidad'),
        ('Administración', 'Almacén Administración', 'Área de Administración', 'Encargado de Administración')
) AS x(especialidad, nombre, ubicacion, responsable)
JOIN mod03.especialidad e
    ON e.nombre = x.especialidad
WHERE NOT EXISTS (
    SELECT 1
    FROM mod03.almacen a
    WHERE a.nombre = x.nombre
);

-- -----------------------------------------------------------------------------
-- CLASIFICACIONES
-- -----------------------------------------------------------------------------

INSERT INTO mod03.clasificaciones_bien (nombre)
VALUES
    ('CPU'),
    ('Monitor'),
    ('Proyector'),
    ('Teclado'),
    ('Mouse'),
    ('Laptop'),
    ('Impresora'),
    ('Switch'),
    ('Estabilizador'),
    ('Pantalla'),
    ('Parlante'),
    ('Mobiliario'),
    ('Otro')
ON CONFLICT (nombre) DO NOTHING;

-- -----------------------------------------------------------------------------
-- AMBIENTES DE DEMOSTRACIÓN
-- -----------------------------------------------------------------------------

INSERT INTO mod03.ambiente (id_especialidad, nombre)
SELECT e.id_especialidad, x.nombre
FROM mod03.especialidad e
JOIN (
    VALUES
        ('Computación e Informática', 'LAB01'),
        ('Computación e Informática', 'LAB02'),
        ('Computación e Informática', 'LAB05'),
        ('Computación e Informática', 'Taller de Redes'),
        ('Computación e Informática', 'Taller de Mantenimiento'),
        ('Computación e Informática', 'Oficina'),
        ('Computación e Informática', 'Aulas'),
        ('Contabilidad', 'Oficina de Contabilidad'),
        ('Contabilidad', 'Aula de Contabilidad'),
        ('Administración', 'Oficina de Administración'),
        ('Administración', 'Aula de Administración')
) AS x(especialidad, nombre)
    ON e.nombre = x.especialidad
ON CONFLICT (id_especialidad, nombre) DO NOTHING;

-- -----------------------------------------------------------------------------
-- BIENES DE DEMOSTRACIÓN
-- -----------------------------------------------------------------------------
-- Se incluyen equipos representativos: CPU, monitor, proyector, teclado,
-- laptop, switch, estabilizador y mobiliario.

INSERT INTO mod03.bien (
    id_almacen,
    id_clasificacion,
    cbi,
    codigo_inventario,
    descripcion,
    marca,
    modelo,
    serie,
    procedencia,
    fecha_ingreso,
    estado,
    observacion
)
SELECT
    a.id_almacen,
    c.id_clasificacion,
    v.cbi,
    v.codigo_inventario,
    v.descripcion,
    v.marca,
    v.modelo,
    v.serie,
    v.procedencia,
    v.fecha_ingreso,
    v.estado,
    v.observacion
FROM (
    VALUES
        ('Almacén General', 'CPU', 'CBI-0250417', 'INV-2025-51463', 'CPU', 'HP', 'EliteDesk 800 G2 SFF', 'MXL6411WH7', 'Donación', DATE '2026-09-01', 'Bueno', 'Equipo de demostración'),
        ('Almacén General', 'CPU', 'CBI-0250418', 'INV-2025-51464', 'CPU', 'HP', 'EliteDesk 800 G2 SFF', 'MXL6411YMK', 'Donación', DATE '2026-09-01', 'Bueno', 'Equipo de demostración'),
        ('Almacén General', 'CPU', 'CBI-0250388', 'INV-2025-51465', 'CPU', 'HP', 'EliteDesk 800 G2', '8CG925G045', 'Donación', DATE '2026-09-02', 'Inoperativo', 'No enciende'),
        ('Almacén General', 'CPU', 'CBI-0250389', 'INV-2025-51466', 'CPU', 'HP', 'EliteDesk 800 G2', 'MXLA43625VK', 'Donación', DATE '2026-09-02', 'En reparación', 'Pendiente de revisión OTIS'),
        ('Almacén General', 'CPU', 'CBI-0250390', 'INV-2025-51467', 'CPU', 'Lenovo', 'V520S', 'PCONZ5S9', 'Donación', DATE '2026-09-02', 'Regular', 'Funcionamiento parcial'),
        ('Almacén General', 'Monitor', 'CBI-0250151', 'INV-2025-51468', 'Monitor', 'HP', 'V244h', 'CNK72906YJ', 'Adquisición', DATE '2026-09-03', 'Bueno', 'Equipo operativo'),
        ('Almacén General', 'Monitor', 'CBI-0250152', 'INV-2025-51469', 'Monitor', 'HP', 'V244h', 'CNK72906YK', 'Adquisición', DATE '2026-09-03', 'Bueno', 'Equipo operativo'),
        ('Almacén General', 'Monitor', 'CBI-0250166', 'INV-2025-51470', 'Monitor', 'HP', 'V244h', 'CNK72906YL', 'Adquisición', DATE '2026-09-03', 'Inoperativo', 'Pantalla sin señal'),
        ('Almacén General', 'Proyector', 'CBI-250508', 'INV-2025-50761', 'Proyector', 'EPSON', 'H553A', 'TQWF480125L', 'Donación', DATE '2026-09-04', 'Bueno', 'Equipo operativo'),
        ('Almacén General', 'Proyector', 'CBI-244663', 'INV-2025-69634', 'Proyector', 'EPSON', 'H553A', 'BUWK45000931', 'Donación', DATE '2026-09-04', 'Bueno', 'Equipo operativo'),
        ('Almacén General', 'Proyector', 'CBI-311492', 'INV-2025-69635', 'Proyector', 'EPSON', 'H553A', 'X28E01000508', 'Donación', DATE '2026-09-04', 'Regular', 'Requiere revisión'),
        ('Almacén General', 'Teclado', 'CBI-250285', 'INV-2025-69069', 'Teclado', 'Genius', 'K639', 'ZM70810080', 'Donación', DATE '2026-09-05', 'Bueno', 'Equipo operativo'),
        ('Almacén General', 'Teclado', 'CBI-250291', 'INV-2025-69070', 'Teclado', 'Genius', 'K639', 'ZM70810081', 'Donación', DATE '2026-09-05', 'Bueno', 'Equipo operativo'),
        ('Almacén General', 'Laptop', 'CBI-403211', 'INV-2025-69789', 'Laptop', 'HP', 'AX201NGW', '5CD219TWT', 'Adquisición', DATE '2026-09-06', 'Bueno', 'Equipo portátil'),
        ('Almacén General', 'Laptop', 'CBI-403209', 'INV-2025-69788', 'Laptop', 'HP', 'AX201NGW', '5CD219F1M', 'Adquisición', DATE '2026-09-06', 'Bueno', 'Equipo portátil'),
        ('Almacén General', 'Laptop', 'CBI-308611', 'INV-2025-51155', 'Laptop', 'Lenovo', 'V520S', 'LR-41NXY', 'Donación', DATE '2026-09-06', 'Regular', 'Equipo de demostración'),
        ('Almacén General', 'Switch', 'CBI-505242', 'INV-2025-69016', 'Switch', 'D-Link', 'DGS-1510-28', 'R2CKIEA000058', 'Donación', DATE '2026-09-07', 'Bueno', 'Equipo de red'),
        ('Almacén General', 'Estabilizador', 'CBI-401624', 'INV-2025-69004', 'Estabilizador', 'Energit', NULL, NULL, 'Donación', DATE '2026-09-07', 'Bueno', 'Equipo operativo'),
        ('Almacén General', 'Parlante', 'CBI-246830', 'INV-2025-49667', 'Parlante', 'Samsung', NULL, NULL, 'Donación', DATE '2026-09-08', 'Inoperativo', 'Equipo sin funcionamiento'),
        ('Almacén General', 'Mobiliario', 'CBI-267653', 'INV-2025-69044', 'Rack', NULL, NULL, NULL, 'Donación', DATE '2026-09-08', 'Bueno', 'Mobiliario institucional'),
        ('Almacén General', 'Mobiliario', 'CBI-250337', 'INV-2025-69093', 'Rack', NULL, NULL, NULL, 'Donación', DATE '2026-09-08', 'Bueno', 'Mobiliario institucional'),
        ('Almacén General', 'Monitor', 'CBI-250376', 'INV-2025-50851', 'Monitor', 'HP', 'HSTND-3731-F', 'BDMEPPC6043M', 'Donación', DATE '2026-09-09', 'Bueno', 'Equipo operativo'),
        ('Almacén General', 'Monitor', 'CBI-250352', 'INV-2025-50890', 'Monitor', 'HP', 'HSTND-3731-F', '3CQ43382BD2', 'Donación', DATE '2026-09-09', 'Bueno', 'Equipo operativo'),
        ('Almacén General', 'CPU', 'CBI-0250421', 'INV-2025-51471', 'CPU', 'HP', '800G1SFF', 'MXL411WGX', 'Donación', DATE '2026-09-10', 'Bueno', 'Equipo operativo'),
        ('Almacén General', 'CPU', 'CBI-0250422', 'INV-2025-51472', 'CPU', 'HP', '800G1SFF', 'MXL411YDJ', 'Donación', DATE '2026-09-10', 'Bueno', 'Equipo operativo'),
        ('Almacén General', 'Proyector', 'CBI-247405', 'INV-2025-69785', 'Proyector', 'EPSON', 'H553A', 'TQWF483134L', 'Donación', DATE '2026-09-10', 'Regular', 'Revisión recomendada'),
        ('Almacén General', 'Teclado', 'CBI-250504', 'INV-2025-69085', 'Teclado', 'Genius', 'K639', 'ZM75MN6651', 'Donación', DATE '2026-09-10', 'Bueno', 'Equipo operativo'),
        ('Almacén General', 'Laptop', 'CBI-403230', 'INV-2025-69786', 'Laptop', 'HP', 'AX201NGW', '5CD219FTX', 'Adquisición', DATE '2026-09-11', 'Bueno', 'Equipo portátil'),
        ('Almacén General', 'Laptop', 'CBI-403229', 'INV-2025-69787', 'Laptop', 'HP', 'AX201NGW', '5CD219FTZC', 'Adquisición', DATE '2026-09-11', 'Bueno', 'Equipo portátil')
) AS v(
    almacen,
    clasificacion,
    cbi,
    codigo_inventario,
    descripcion,
    marca,
    modelo,
    serie,
    procedencia,
    fecha_ingreso,
    estado,
    observacion
)
JOIN mod03.almacen a
    ON a.nombre = v.almacen
JOIN mod03.clasificaciones_bien c
    ON c.nombre = v.clasificacion
ON CONFLICT DO NOTHING;

-- -----------------------------------------------------------------------------
-- BIENES DE CONTABILIDAD Y ADMINISTRACIÓN PARA LA DEMOSTRACIÓN
-- -----------------------------------------------------------------------------

INSERT INTO mod03.bien (
    id_almacen,
    id_clasificacion,
    cbi,
    codigo_inventario,
    descripcion,
    marca,
    modelo,
    serie,
    procedencia,
    fecha_ingreso,
    estado,
    observacion
)
SELECT
    a.id_almacen,
    c.id_clasificacion,
    v.cbi,
    v.codigo_inventario,
    v.descripcion,
    v.marca,
    v.modelo,
    v.serie,
    v.procedencia,
    v.fecha_ingreso,
    v.estado,
    v.observacion
FROM (
    VALUES
        ('Almacén Contabilidad', 'CPU', 'CBI-CONT-001', 'INV-2026-C001', 'CPU', 'HP', 'ProDesk', 'CONT-S001', 'Donación', DATE '2026-09-12', 'Bueno', 'Dato de demostración'),
        ('Almacén Contabilidad', 'Monitor', 'CBI-CONT-002', 'INV-2026-C002', 'Monitor', 'HP', 'V244h', 'CONT-M001', 'Donación', DATE '2026-09-12', 'Regular', 'Dato de demostración'),
        ('Almacén Contabilidad', 'Laptop', 'CBI-CONT-003', 'INV-2026-C003', 'Laptop', 'Lenovo', 'V520S', 'CONT-L001', 'Adquisición', DATE '2026-09-12', 'Bueno', 'Dato de demostración'),
        ('Almacén Administración', 'CPU', 'CBI-ADM-001', 'INV-2026-A001', 'CPU', 'HP', 'EliteDesk 800', 'ADM-S001', 'Donación', DATE '2026-09-13', 'Bueno', 'Dato de demostración'),
        ('Almacén Administración', 'Proyector', 'CBI-ADM-002', 'INV-2026-A002', 'Proyector', 'EPSON', 'H553A', 'ADM-P001', 'Adquisición', DATE '2026-09-13', 'Regular', 'Dato de demostración'),
        ('Almacén Administración', 'Monitor', 'CBI-ADM-003', 'INV-2026-A003', 'Monitor', 'HP', 'V244h', 'ADM-M001', 'Donación', DATE '2026-09-13', 'Inoperativo', 'Dato de demostración')
) AS v(
    almacen,
    clasificacion,
    cbi,
    codigo_inventario,
    descripcion,
    marca,
    modelo,
    serie,
    procedencia,
    fecha_ingreso,
    estado,
    observacion
)
JOIN mod03.almacen a
    ON a.nombre = v.almacen
JOIN mod03.clasificaciones_bien c
    ON c.nombre = v.clasificacion
ON CONFLICT DO NOTHING;

-- -----------------------------------------------------------------------------
-- ASIGNACIONES DE DEMOSTRACIÓN
-- -----------------------------------------------------------------------------

INSERT INTO mod03.asignacion (
    id_bien,
    id_ambiente,
    responsable,
    fecha_asignacion,
    estado,
    observacion
)
SELECT
    b.id_bien,
    am.id_ambiente,
    v.responsable,
    v.fecha_asignacion,
    'Activa',
    v.observacion
FROM (
    VALUES
        ('CBI-0250417', 'LAB01', 'Encargado de LAB01', DATE '2026-09-15', 'Equipo instalado para demostración'),
        ('CBI-0250418', 'LAB01', 'Encargado de LAB01', DATE '2026-09-15', 'Equipo instalado para demostración'),
        ('CBI-0250151', 'LAB02', 'Encargado de LAB02', DATE '2026-09-15', 'Monitor asignado'),
        ('CBI-250508', 'Aulas', 'Encargado de Aulas', DATE '2026-09-16', 'Proyector asignado'),
        ('CBI-403211', 'Oficina', 'Responsable de Oficina', DATE '2026-09-16', 'Laptop asignada'),
        ('CBI-505242', 'Taller de Redes', 'Encargado de Redes', DATE '2026-09-16', 'Switch asignado')
) AS v(cbi, ambiente, responsable, fecha_asignacion, observacion)
JOIN mod03.bien b
    ON b.cbi = v.cbi
JOIN mod03.ambiente am
    ON am.nombre = v.ambiente
JOIN mod03.especialidad e
    ON e.id_especialidad = am.id_especialidad
WHERE e.nombre = 'Computación e Informática'
  AND NOT EXISTS (
      SELECT 1
      FROM mod03.asignacion ax
      WHERE ax.id_bien = b.id_bien
        AND ax.estado = 'Activa'
  );

-- -----------------------------------------------------------------------------
-- TRANSFERENCIAS DE DEMOSTRACIÓN
-- -----------------------------------------------------------------------------

INSERT INTO mod03.transferencia (
    id_bien,
    id_almacen_origen,
    id_almacen_destino,
    fecha_solicitud,
    fecha_salida,
    fecha_recepcion,
    motivo,
    responsable_origen,
    responsable_destino,
    estado_movimiento,
    documento,
    observacion
)
SELECT
    b.id_bien,
    ao.id_almacen,
    ad.id_almacen,
    v.fecha_solicitud,
    v.fecha_salida,
    v.fecha_recepcion,
    v.motivo,
    v.responsable_origen,
    v.responsable_destino,
    v.estado_movimiento,
    v.documento,
    v.observacion
FROM (
    VALUES
        ('CBI-0250417', 'Almacén General', 'Almacén Computación', TIMESTAMPTZ '2026-09-17 09:00:00-05', TIMESTAMPTZ '2026-09-17 10:00:00-05', TIMESTAMPTZ '2026-09-17 10:30:00-05', 'Requerimiento de equipo', 'Eduardo - Patrimoniales', 'Encargado de Computación', 'Recepcionado', 'TRF-2026-001', 'Transferencia completada'),
        ('CBI-250508', 'Almacén General', 'Almacén Computación', TIMESTAMPTZ '2026-09-18 09:00:00-05', TIMESTAMPTZ '2026-09-18 10:00:00-05', NULL, 'Requerimiento de proyector', 'Eduardo - Patrimoniales', 'Encargado de Aulas', 'Pendiente de recepción', 'TRF-2026-002', 'Esperando aceptación del destino'),
        ('CBI-403211', 'Almacén General', 'Almacén Computación', TIMESTAMPTZ '2026-09-18 11:00:00-05', TIMESTAMPTZ '2026-09-18 11:30:00-05', NULL, 'Asignación de laptop', 'Eduardo - Patrimoniales', 'Responsable de Oficina', 'En tránsito', 'TRF-2026-003', 'Equipo en traslado')
) AS v(
    cbi,
    almacen_origen,
    almacen_destino,
    fecha_solicitud,
    fecha_salida,
    fecha_recepcion,
    motivo,
    responsable_origen,
    responsable_destino,
    estado_movimiento,
    documento,
    observacion
)
JOIN mod03.bien b
    ON b.cbi = v.cbi
JOIN mod03.almacen ao
    ON ao.nombre = v.almacen_origen
JOIN mod03.almacen ad
    ON ad.nombre = v.almacen_destino
WHERE NOT EXISTS (
    SELECT 1
    FROM mod03.transferencia t
    WHERE t.documento = v.documento
);

-- -----------------------------------------------------------------------------
-- INVENTARIO ANUAL DE DEMOSTRACIÓN
-- -----------------------------------------------------------------------------

INSERT INTO mod03.inventario_anual (
    id_bien,
    anio,
    fecha_verificacion,
    resultado,
    observacion
)
SELECT
    b.id_bien,
    v.anio,
    v.fecha_verificacion,
    v.resultado,
    v.observacion
FROM (
    VALUES
        ('CBI-0250417', 2026, DATE '2026-09-20', 'Físico', 'Equipo ubicado y verificado'),
        ('CBI-0250418', 2026, DATE '2026-09-20', 'Físico', 'Equipo ubicado y verificado'),
        ('CBI-0250388', 2026, DATE '2026-09-20', 'Físico', 'Equipo ubicado, estado inoperativo'),
        ('CBI-250508', 2026, DATE '2026-09-20', 'Físico', 'Proyector verificado'),
        ('CBI-403211', 2026, DATE '2026-09-21', 'Físico', 'Laptop verificada'),
        ('CBI-505242', 2026, DATE '2026-09-21', 'Físico', 'Switch verificado'),
        ('CBI-250376', 2026, DATE '2026-09-21', 'Faltante', 'No ubicado durante verificación de demostración'),
        ('CBI-250352', 2026, DATE '2026-09-21', 'Sobrante', 'Bien encontrado sin registro previo de ubicación')
) AS v(cbi, anio, fecha_verificacion, resultado, observacion)
JOIN mod03.bien b
    ON b.cbi = v.cbi
ON CONFLICT (id_bien, anio) DO NOTHING;

-- =============================================================================
-- FIN DE DATOS DE DEMOSTRACIÓN
-- =============================================================================

-- =============================================================================
-- FIN DEL SCHEMA STOCKCODE - MODULO 03
-- =============================================================================
